// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAPIKey(arg1) {
  return window['go']['api']['App']['CreateAPIKey'](arg1);
}

export function CreateProvider(arg1) {
  return window['go']['api']['App']['CreateProvider'](arg1);
}

export function CreateRoute(arg1) {
  return window['go']['api']['App']['CreateRoute'](arg1);
}

export function DeleteAPIKey(arg1) {
  return window['go']['api']['App']['DeleteAPIKey'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['api']['App']['DeleteProvider'](arg1);
}

export function DeleteRoute(arg1) {
  return window['go']['api']['App']['DeleteRoute'](arg1);
}

export function ExportData(arg1) {
  return window['go']['api']['App']['ExportData'](arg1);
}

export function FetchUpstreamModels(arg1) {
  return window['go']['api']['App']['FetchUpstreamModels'](arg1);
}

export function GetChartAggregates(arg1) {
  return window['go']['api']['App']['GetChartAggregates'](arg1);
}

export function GetDashboard() {
  return window['go']['api']['App']['GetDashboard']();
}

export function GetProvider(arg1) {
  return window['go']['api']['App']['GetProvider'](arg1);
}

export function GetProxyStatus() {
  return window['go']['api']['App']['GetProxyStatus']();
}

export function GetRoute(arg1) {
  return window['go']['api']['App']['GetRoute'](arg1);
}

export function GetSettings() {
  return window['go']['api']['App']['GetSettings']();
}

export function GetSystemHealth() {
  return window['go']['api']['App']['GetSystemHealth']();
}

export function GetUsageStats() {
  return window['go']['api']['App']['GetUsageStats']();
}

export function ListAPIKeys() {
  return window['go']['api']['App']['ListAPIKeys']();
}

export function ListEndpoints() {
  return window['go']['api']['App']['ListEndpoints']();
}

export function ListModels(arg1) {
  return window['go']['api']['App']['ListModels'](arg1);
}

export function ListProviders() {
  return window['go']['api']['App']['ListProviders']();
}

export function ListRoutes() {
  return window['go']['api']['App']['ListRoutes']();
}

export function PurgeLogs(arg1) {
  return window['go']['api']['App']['PurgeLogs'](arg1);
}

export function QueryLogs(arg1) {
  return window['go']['api']['App']['QueryLogs'](arg1);
}

export function ReorderRoutes(arg1) {
  return window['go']['api']['App']['ReorderRoutes'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['api']['App']['SaveSettings'](arg1);
}

export function SetModelsActive(arg1, arg2, arg3) {
  return window['go']['api']['App']['SetModelsActive'](arg1, arg2, arg3);
}

export function TestAllProviders() {
  return window['go']['api']['App']['TestAllProviders']();
}

export function TestModelLatency(arg1, arg2) {
  return window['go']['api']['App']['TestModelLatency'](arg1, arg2);
}

export function TestProvider(arg1) {
  return window['go']['api']['App']['TestProvider'](arg1);
}

export function UpdateAPIKey(arg1, arg2) {
  return window['go']['api']['App']['UpdateAPIKey'](arg1, arg2);
}

export function UpdateProvider(arg1, arg2) {
  return window['go']['api']['App']['UpdateProvider'](arg1, arg2);
}

export function UpdateRoute(arg1, arg2) {
  return window['go']['api']['App']['UpdateRoute'](arg1, arg2);
}
