// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProviderModels(arg1, arg2) {
  return window['go']['api']['App']['AddProviderModels'](arg1, arg2);
}

export function ApplyOmoSlimConfig(arg1, arg2) {
  return window['go']['api']['App']['ApplyOmoSlimConfig'](arg1, arg2);
}

export function ApplyOpencodeConfigChange(arg1, arg2) {
  return window['go']['api']['App']['ApplyOpencodeConfigChange'](arg1, arg2);
}

export function ApplyToolConfigChange(arg1, arg2, arg3) {
  return window['go']['api']['App']['ApplyToolConfigChange'](arg1, arg2, arg3);
}

export function CancelModelTest(arg1) {
  return window['go']['api']['App']['CancelModelTest'](arg1);
}

export function CheckToolDrift(arg1) {
  return window['go']['api']['App']['CheckToolDrift'](arg1);
}

export function ClearLogs() {
  return window['go']['api']['App']['ClearLogs']();
}

export function ClearProviderModels(arg1) {
  return window['go']['api']['App']['ClearProviderModels'](arg1);
}

export function CreateAPIKey(arg1) {
  return window['go']['api']['App']['CreateAPIKey'](arg1);
}

export function CreateModelRule(arg1) {
  return window['go']['api']['App']['CreateModelRule'](arg1);
}

export function CreateProvider(arg1) {
  return window['go']['api']['App']['CreateProvider'](arg1);
}

export function CreateToolPreset(arg1, arg2) {
  return window['go']['api']['App']['CreateToolPreset'](arg1, arg2);
}

export function DeleteAPIKey(arg1) {
  return window['go']['api']['App']['DeleteAPIKey'](arg1);
}

export function DeleteModel(arg1, arg2) {
  return window['go']['api']['App']['DeleteModel'](arg1, arg2);
}

export function DeleteModelCapability(arg1, arg2, arg3, arg4) {
  return window['go']['api']['App']['DeleteModelCapability'](arg1, arg2, arg3, arg4);
}

export function DeleteModelRule(arg1) {
  return window['go']['api']['App']['DeleteModelRule'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['api']['App']['DeleteProvider'](arg1);
}

export function DeleteProviderFeatureCapability(arg1, arg2, arg3) {
  return window['go']['api']['App']['DeleteProviderFeatureCapability'](arg1, arg2, arg3);
}

export function DeleteToolPreset(arg1) {
  return window['go']['api']['App']['DeleteToolPreset'](arg1);
}

export function DisableToolPreset(arg1, arg2) {
  return window['go']['api']['App']['DisableToolPreset'](arg1, arg2);
}

export function EnableToolPreset(arg1) {
  return window['go']['api']['App']['EnableToolPreset'](arg1);
}

export function EnterBackground() {
  return window['go']['api']['App']['EnterBackground']();
}

export function EnterForeground() {
  return window['go']['api']['App']['EnterForeground']();
}

export function ExportData(arg1) {
  return window['go']['api']['App']['ExportData'](arg1);
}

export function ExportToolSnippet(arg1) {
  return window['go']['api']['App']['ExportToolSnippet'](arg1);
}

export function FetchUpstreamModels(arg1) {
  return window['go']['api']['App']['FetchUpstreamModels'](arg1);
}

export function GetAppInfo() {
  return window['go']['api']['App']['GetAppInfo']();
}

export function GetAppVisibilityState() {
  return window['go']['api']['App']['GetAppVisibilityState']();
}

export function GetDashboard() {
  return window['go']['api']['App']['GetDashboard']();
}

export function GetLocalIPv4Addresses() {
  return window['go']['api']['App']['GetLocalIPv4Addresses']();
}

export function GetModelRule(arg1) {
  return window['go']['api']['App']['GetModelRule'](arg1);
}

export function GetModelRuleShadowComparisons() {
  return window['go']['api']['App']['GetModelRuleShadowComparisons']();
}

export function GetOmoSlimConfig() {
  return window['go']['api']['App']['GetOmoSlimConfig']();
}

export function GetOpencodeGlobalSettings() {
  return window['go']['api']['App']['GetOpencodeGlobalSettings']();
}

export function GetOpencodeLiveState() {
  return window['go']['api']['App']['GetOpencodeLiveState']();
}

export function GetProvider(arg1) {
  return window['go']['api']['App']['GetProvider'](arg1);
}

export function GetProviderKey(arg1) {
  return window['go']['api']['App']['GetProviderKey'](arg1);
}

export function GetProxyStatus() {
  return window['go']['api']['App']['GetProxyStatus']();
}

export function GetRequestLog(arg1) {
  return window['go']['api']['App']['GetRequestLog'](arg1);
}

export function GetRuntimePaths() {
  return window['go']['api']['App']['GetRuntimePaths']();
}

export function GetSettings() {
  return window['go']['api']['App']['GetSettings']();
}

export function GetSystemHealth() {
  return window['go']['api']['App']['GetSystemHealth']();
}

export function GetTargetBreakerStatuses() {
  return window['go']['api']['App']['GetTargetBreakerStatuses']();
}

export function GetTargetDiagnostics() {
  return window['go']['api']['App']['GetTargetDiagnostics']();
}

export function GetToolCommonConfig(arg1) {
  return window['go']['api']['App']['GetToolCommonConfig'](arg1);
}

export function GetUsageStats(arg1) {
  return window['go']['api']['App']['GetUsageStats'](arg1);
}

export function GetUsageTrends(arg1) {
  return window['go']['api']['App']['GetUsageTrends'](arg1);
}

export function HideApp() {
  return window['go']['api']['App']['HideApp']();
}

export function HideWindow() {
  return window['go']['api']['App']['HideWindow']();
}

export function IsQuitting() {
  return window['go']['api']['App']['IsQuitting']();
}

export function ListAPIKeys() {
  return window['go']['api']['App']['ListAPIKeys']();
}

export function ListEndpoints() {
  return window['go']['api']['App']['ListEndpoints']();
}

export function ListModelCapabilities(arg1, arg2) {
  return window['go']['api']['App']['ListModelCapabilities'](arg1, arg2);
}

export function ListModelRules() {
  return window['go']['api']['App']['ListModelRules']();
}

export function ListModels(arg1) {
  return window['go']['api']['App']['ListModels'](arg1);
}

export function ListProviderCapabilities(arg1) {
  return window['go']['api']['App']['ListProviderCapabilities'](arg1);
}

export function ListProviders() {
  return window['go']['api']['App']['ListProviders']();
}

export function ListToolBackups(arg1) {
  return window['go']['api']['App']['ListToolBackups'](arg1);
}

export function ListToolPresets(arg1) {
  return window['go']['api']['App']['ListToolPresets'](arg1);
}

export function ListToolProviders(arg1) {
  return window['go']['api']['App']['ListToolProviders'](arg1);
}

export function ListToolStatuses() {
  return window['go']['api']['App']['ListToolStatuses']();
}

export function ListUpstreamMonitorModels() {
  return window['go']['api']['App']['ListUpstreamMonitorModels']();
}

export function NavigateTo(arg1) {
  return window['go']['api']['App']['NavigateTo'](arg1);
}

export function OpenStorageFolder() {
  return window['go']['api']['App']['OpenStorageFolder']();
}

export function PingLogEvent() {
  return window['go']['api']['App']['PingLogEvent']();
}

export function PreviewOpencodeConfigChange(arg1) {
  return window['go']['api']['App']['PreviewOpencodeConfigChange'](arg1);
}

export function PreviewToolConfigChange(arg1, arg2) {
  return window['go']['api']['App']['PreviewToolConfigChange'](arg1, arg2);
}

export function PreviewToolOmoSlimChange(arg1) {
  return window['go']['api']['App']['PreviewToolOmoSlimChange'](arg1);
}

export function ProbeUpstreamMonitorModel(arg1) {
  return window['go']['api']['App']['ProbeUpstreamMonitorModel'](arg1);
}

export function ProbeUpstreamMonitorModels(arg1) {
  return window['go']['api']['App']['ProbeUpstreamMonitorModels'](arg1);
}

export function PurgeLogs(arg1) {
  return window['go']['api']['App']['PurgeLogs'](arg1);
}

export function QueryLogs(arg1) {
  return window['go']['api']['App']['QueryLogs'](arg1);
}

export function QueryLogsLite(arg1) {
  return window['go']['api']['App']['QueryLogsLite'](arg1);
}

export function Quit() {
  return window['go']['api']['App']['Quit']();
}

export function ReorderModelRuleTargets(arg1, arg2) {
  return window['go']['api']['App']['ReorderModelRuleTargets'](arg1, arg2);
}

export function ReorderModelRules(arg1) {
  return window['go']['api']['App']['ReorderModelRules'](arg1);
}

export function ReplayLog(arg1) {
  return window['go']['api']['App']['ReplayLog'](arg1);
}

export function ResetSettings() {
  return window['go']['api']['App']['ResetSettings']();
}

export function ResetTargetBreakers() {
  return window['go']['api']['App']['ResetTargetBreakers']();
}

export function RestartProxy() {
  return window['go']['api']['App']['RestartProxy']();
}

export function RestoreToolBackup(arg1, arg2, arg3) {
  return window['go']['api']['App']['RestoreToolBackup'](arg1, arg2, arg3);
}

export function RevealToolProviderKey(arg1, arg2) {
  return window['go']['api']['App']['RevealToolProviderKey'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['api']['App']['SaveSettings'](arg1);
}

export function SetAPIKeyEnabled(arg1, arg2) {
  return window['go']['api']['App']['SetAPIKeyEnabled'](arg1, arg2);
}

export function SetAppInfo(arg1) {
  return window['go']['api']['App']['SetAppInfo'](arg1);
}

export function SetInitialVisibility(arg1) {
  return window['go']['api']['App']['SetInitialVisibility'](arg1);
}

export function SetModelCapability(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['api']['App']['SetModelCapability'](arg1, arg2, arg3, arg4, arg5);
}

export function SetModelsActive(arg1, arg2, arg3) {
  return window['go']['api']['App']['SetModelsActive'](arg1, arg2, arg3);
}

export function SetProviderCapability(arg1, arg2, arg3) {
  return window['go']['api']['App']['SetProviderCapability'](arg1, arg2, arg3);
}

export function SetProviderEnabled(arg1, arg2) {
  return window['go']['api']['App']['SetProviderEnabled'](arg1, arg2);
}

export function SetProviderFeatureCapability(arg1, arg2, arg3, arg4) {
  return window['go']['api']['App']['SetProviderFeatureCapability'](arg1, arg2, arg3, arg4);
}

export function ShowApp() {
  return window['go']['api']['App']['ShowApp']();
}

export function ShowWindow() {
  return window['go']['api']['App']['ShowWindow']();
}

export function Shutdown(arg1) {
  return window['go']['api']['App']['Shutdown'](arg1);
}

export function StartProxy() {
  return window['go']['api']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['api']['App']['StopProxy']();
}

export function TestAllProviders() {
  return window['go']['api']['App']['TestAllProviders']();
}

export function TestModelChat(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['api']['App']['TestModelChat'](arg1, arg2, arg3, arg4, arg5);
}

export function TestModelLatency(arg1, arg2) {
  return window['go']['api']['App']['TestModelLatency'](arg1, arg2);
}

export function TestProvider(arg1) {
  return window['go']['api']['App']['TestProvider'](arg1);
}

export function UpdateAPIKey(arg1, arg2) {
  return window['go']['api']['App']['UpdateAPIKey'](arg1, arg2);
}

export function UpdateEnabledToolPreset(arg1, arg2) {
  return window['go']['api']['App']['UpdateEnabledToolPreset'](arg1, arg2);
}

export function UpdateModelRule(arg1, arg2) {
  return window['go']['api']['App']['UpdateModelRule'](arg1, arg2);
}

export function UpdateProvider(arg1, arg2) {
  return window['go']['api']['App']['UpdateProvider'](arg1, arg2);
}

export function UpdateProviderModel(arg1) {
  return window['go']['api']['App']['UpdateProviderModel'](arg1);
}

export function UpdateToolPreset(arg1, arg2) {
  return window['go']['api']['App']['UpdateToolPreset'](arg1, arg2);
}
