// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {toolconfig} from '../models';
import {service} from '../models';
import {model} from '../models';
import {api} from '../models';
import {proxy} from '../models';
import {context} from '../models';

export function AddProviderModels(arg1:string,arg2:Array<string>):Promise<void>;

export function ApplyOmoConfig(arg1:toolconfig.OmoChange,arg2:boolean):Promise<void>;

export function ApplyToolPreset(arg1:number,arg2:boolean):Promise<service.ToolApplyResult>;

export function CancelModelTest(arg1:string):Promise<boolean>;

export function CheckToolDrift(arg1:string):Promise<Array<service.DriftState>>;

export function ClearLogs():Promise<number>;

export function ClearProviderModels(arg1:string):Promise<void>;

export function CreateAPIKey(arg1:model.ApiKeyInput):Promise<model.ApiKey>;

export function CreateModelRule(arg1:model.ModelRuleInput):Promise<model.ModelRule>;

export function CreateProvider(arg1:model.ProviderInput):Promise<model.Provider>;

export function CreateToolPreset(arg1:toolconfig.Preset,arg2:string):Promise<toolconfig.Preset>;

export function DeleteAPIKey(arg1:string):Promise<void>;

export function DeleteModel(arg1:string,arg2:string):Promise<void>;

export function DeleteModelCapability(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteModelRule(arg1:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function DeleteProviderFeatureCapability(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteToolPreset(arg1:number):Promise<void>;

export function EnterBackground():Promise<void>;

export function EnterForeground():Promise<void>;

export function ExportData(arg1:model.ExportFormat):Promise<api.ExportResult>;

export function ExportToolSnippet(arg1:number):Promise<toolconfig.Snippet>;

export function FetchUpstreamModels(arg1:string):Promise<Array<model.Model>>;

export function GetAppInfo():Promise<model.AppInfo>;

export function GetAppVisibilityState():Promise<string>;

export function GetDashboard():Promise<model.DashboardData>;

export function GetModelRule(arg1:string):Promise<model.ModelRule>;

export function GetModelRuleShadowComparisons():Promise<Array<model.ModelRuleShadowComparison>>;

export function GetOmoConfig():Promise<service.OmoConfigView>;

export function GetProvider(arg1:string):Promise<model.Provider>;

export function GetProviderKey(arg1:string):Promise<string>;

export function GetProxyStatus():Promise<api.ProxyStatus>;

export function GetRequestLog(arg1:string):Promise<model.RequestLog>;

export function GetRuntimePaths():Promise<api.RuntimePaths>;

export function GetSettings():Promise<model.Settings>;

export function GetSystemHealth():Promise<model.ServiceHealth>;

export function GetTargetBreakerStatuses():Promise<Array<proxy.TargetBreakerStatus>>;

export function GetTargetDiagnostics():Promise<Array<model.TargetShadowScore>>;

export function GetUsageStats(arg1:model.LogQuery):Promise<model.UsageStats>;

export function GetUsageTrends(arg1:model.UsageTrendsQuery):Promise<model.UsageTrends>;

export function HideApp():Promise<void>;

export function HideWindow():Promise<void>;

export function ImportToolPreset(arg1:string,arg2:string,arg3:string):Promise<toolconfig.Preset>;

export function IsQuitting():Promise<boolean>;

export function ListAPIKeys():Promise<Array<model.ApiKey>>;

export function ListEndpoints():Promise<Array<model.Endpoint>>;

export function ListModelCapabilities(arg1:string,arg2:string):Promise<Array<model.ModelCapability>>;

export function ListModelRules():Promise<Array<model.ModelRule>>;

export function ListModels(arg1:string):Promise<Array<model.Model>>;

export function ListProviderCapabilities(arg1:string):Promise<Array<model.ProviderCapability>>;

export function ListProviders():Promise<Array<model.Provider>>;

export function ListToolBackups(arg1:string):Promise<Array<service.ToolBackupInfo>>;

export function ListToolPresets(arg1:string):Promise<Array<toolconfig.Preset>>;

export function ListToolStatuses():Promise<Array<toolconfig.ToolStatus>>;

export function ListUpstreamMonitorModels():Promise<Array<model.UpstreamMonitorModel>>;

export function NavigateTo(arg1:string):Promise<void>;

export function OpenStorageFolder():Promise<void>;

export function PingLogEvent():Promise<void>;

export function ProbeUpstreamMonitorModel(arg1:model.UpstreamMonitorSelection):Promise<model.UpstreamMonitorResult>;

export function ProbeUpstreamMonitorModels(arg1:Array<model.UpstreamMonitorSelection>):Promise<model.UpstreamMonitorBatch>;

export function PurgeLogs(arg1:number):Promise<number>;

export function QueryLogs(arg1:model.LogQuery):Promise<model.LogQueryResult>;

export function QueryLogsLite(arg1:model.LogQuery):Promise<model.LogQueryResult>;

export function Quit():Promise<void>;

export function ReorderModelRuleTargets(arg1:string,arg2:Array<string>):Promise<model.ReorderModelRuleTargetsResult>;

export function ReorderModelRules(arg1:Array<string>):Promise<model.ReorderModelRulesResult>;

export function ReplayLog(arg1:string):Promise<model.ReplayResult>;

export function ResetSettings():Promise<model.Settings>;

export function ResetTargetBreakers():Promise<void>;

export function RestartProxy():Promise<void>;

export function RestoreToolBackup(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSettings(arg1:model.Settings):Promise<void>;

export function SetAPIKeyEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetAppInfo(arg1:model.AppInfo):Promise<void>;

export function SetInitialVisibility(arg1:boolean):Promise<void>;

export function SetModelCapability(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SetModelsActive(arg1:string,arg2:Array<string>,arg3:boolean):Promise<void>;

export function SetProviderCapability(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetProviderEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetProviderFeatureCapability(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ShowApp():Promise<void>;

export function ShowWindow():Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function TestAllProviders():Promise<Array<model.ProviderTestResult>>;

export function TestModelChat(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:string):Promise<model.ModelChatTestResult>;

export function TestModelLatency(arg1:string,arg2:string):Promise<model.ModelTestResult>;

export function TestProvider(arg1:string):Promise<model.ProviderTestResult>;

export function UpdateAPIKey(arg1:string,arg2:model.ApiKeyInput):Promise<model.ApiKey>;

export function UpdateModelRule(arg1:string,arg2:model.ModelRuleInput):Promise<model.ModelRule>;

export function UpdateProvider(arg1:string,arg2:model.ProviderInput):Promise<model.Provider>;

export function UpdateProviderModel(arg1:model.ProviderModelUpdate):Promise<void>;

export function UpdateToolPreset(arg1:toolconfig.Preset,arg2:string):Promise<toolconfig.Preset>;
