// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {api} from '../models';

export function CreateAPIKey(arg1:model.ApiKeyInput):Promise<model.ApiKey>;

export function CreateProvider(arg1:model.ProviderInput):Promise<model.Provider>;

export function CreateRoute(arg1:model.RouteInput):Promise<model.Route>;

export function DeleteAPIKey(arg1:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function DeleteRoute(arg1:string):Promise<void>;

export function ExportData(arg1:model.ExportFormat):Promise<api.ExportResult>;

export function FetchUpstreamModels(arg1:string):Promise<Array<model.Model>>;

export function GetDashboard():Promise<model.DashboardData>;

export function GetProvider(arg1:string):Promise<model.Provider>;

export function GetProxyStatus():Promise<api.ProxyStatus>;

export function GetRoute(arg1:string):Promise<model.Route>;

export function GetSettings():Promise<model.Settings>;

export function GetSystemHealth():Promise<model.ServiceHealth>;

export function GetUsageStats():Promise<model.UsageStats>;

export function GetUsageTrends(arg1:model.UsageTrendsQuery):Promise<model.UsageTrends>;

export function ListAPIKeys():Promise<Array<model.ApiKey>>;

export function ListEndpoints():Promise<Array<model.Endpoint>>;

export function ListModels(arg1:string):Promise<Array<model.Model>>;

export function ListProviders():Promise<Array<model.Provider>>;

export function ListRoutes():Promise<Array<model.Route>>;

export function OpenStorageFolder():Promise<void>;

export function PurgeLogs(arg1:number):Promise<number>;

export function QueryLogs(arg1:model.LogQuery):Promise<model.LogQueryResult>;

export function ReorderRoutes(arg1:Array<string>):Promise<void>;

export function SaveSettings(arg1:model.Settings):Promise<void>;

export function SetModelsActive(arg1:string,arg2:Array<string>,arg3:boolean):Promise<void>;

export function TestAllProviders():Promise<Array<model.ProviderTestResult>>;

export function TestModelLatency(arg1:string,arg2:string):Promise<model.ModelTestResult>;

export function TestProvider(arg1:string):Promise<model.ProviderTestResult>;

export function UpdateAPIKey(arg1:string,arg2:model.ApiKeyInput):Promise<model.ApiKey>;

export function UpdateProvider(arg1:string,arg2:model.ProviderInput):Promise<model.Provider>;

export function UpdateRoute(arg1:string,arg2:model.RouteInput):Promise<model.Route>;
