// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProviderModels(arg1, arg2) {
  return window['go']['api']['App']['AddProviderModels'](arg1, arg2);
}

export function ClearLogs() {
  return window['go']['api']['App']['ClearLogs']();
}

export function ClearProviderModels(arg1) {
  return window['go']['api']['App']['ClearProviderModels'](arg1);
}

export function CreateAPIKey(arg1) {
  return window['go']['api']['App']['CreateAPIKey'](arg1);
}

export function CreateModelRule(arg1) {
  return window['go']['api']['App']['CreateModelRule'](arg1);
}

export function CreateProvider(arg1) {
  return window['go']['api']['App']['CreateProvider'](arg1);
}

export function DeleteAPIKey(arg1) {
  return window['go']['api']['App']['DeleteAPIKey'](arg1);
}

export function DeleteModel(arg1, arg2) {
  return window['go']['api']['App']['DeleteModel'](arg1, arg2);
}

export function DeleteModelRule(arg1) {
  return window['go']['api']['App']['DeleteModelRule'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['api']['App']['DeleteProvider'](arg1);
}

export function ExportData(arg1) {
  return window['go']['api']['App']['ExportData'](arg1);
}

export function FetchUpstreamModels(arg1) {
  return window['go']['api']['App']['FetchUpstreamModels'](arg1);
}

export function GetDashboard() {
  return window['go']['api']['App']['GetDashboard']();
}

export function GetModelRule(arg1) {
  return window['go']['api']['App']['GetModelRule'](arg1);
}

export function GetProvider(arg1) {
  return window['go']['api']['App']['GetProvider'](arg1);
}

export function GetProviderKey(arg1) {
  return window['go']['api']['App']['GetProviderKey'](arg1);
}

export function GetProxyStatus() {
  return window['go']['api']['App']['GetProxyStatus']();
}

export function GetRuntimePaths() {
  return window['go']['api']['App']['GetRuntimePaths']();
}

export function GetSettings() {
  return window['go']['api']['App']['GetSettings']();
}

export function GetSystemHealth() {
  return window['go']['api']['App']['GetSystemHealth']();
}

export function GetUsageStats(arg1) {
  return window['go']['api']['App']['GetUsageStats'](arg1);
}

export function GetUsageTrends(arg1) {
  return window['go']['api']['App']['GetUsageTrends'](arg1);
}

export function HideWindow() {
  return window['go']['api']['App']['HideWindow']();
}

export function ListAPIKeys() {
  return window['go']['api']['App']['ListAPIKeys']();
}

export function ListEndpoints() {
  return window['go']['api']['App']['ListEndpoints']();
}

export function ListModelRules() {
  return window['go']['api']['App']['ListModelRules']();
}

export function ListModels(arg1) {
  return window['go']['api']['App']['ListModels'](arg1);
}

export function ListProviders() {
  return window['go']['api']['App']['ListProviders']();
}

export function NavigateTo(arg1) {
  return window['go']['api']['App']['NavigateTo'](arg1);
}

export function OpenStorageFolder() {
  return window['go']['api']['App']['OpenStorageFolder']();
}

export function PingLogEvent() {
  return window['go']['api']['App']['PingLogEvent']();
}

export function PurgeLogs(arg1) {
  return window['go']['api']['App']['PurgeLogs'](arg1);
}

export function QueryLogs(arg1) {
  return window['go']['api']['App']['QueryLogs'](arg1);
}

export function Quit() {
  return window['go']['api']['App']['Quit']();
}

export function ReorderModelRuleTargets(arg1, arg2) {
  return window['go']['api']['App']['ReorderModelRuleTargets'](arg1, arg2);
}

export function ReorderModelRules(arg1) {
  return window['go']['api']['App']['ReorderModelRules'](arg1);
}

export function ResetSettings() {
  return window['go']['api']['App']['ResetSettings']();
}

export function RestartProxy() {
  return window['go']['api']['App']['RestartProxy']();
}

export function SaveSettings(arg1) {
  return window['go']['api']['App']['SaveSettings'](arg1);
}

export function SetModelsActive(arg1, arg2, arg3) {
  return window['go']['api']['App']['SetModelsActive'](arg1, arg2, arg3);
}

export function ShowWindow() {
  return window['go']['api']['App']['ShowWindow']();
}

export function Shutdown(arg1) {
  return window['go']['api']['App']['Shutdown'](arg1);
}

export function StartProxy() {
  return window['go']['api']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['api']['App']['StopProxy']();
}

export function TestAllProviders() {
  return window['go']['api']['App']['TestAllProviders']();
}

export function TestModelLatency(arg1, arg2) {
  return window['go']['api']['App']['TestModelLatency'](arg1, arg2);
}

export function TestProvider(arg1) {
  return window['go']['api']['App']['TestProvider'](arg1);
}

export function UpdateAPIKey(arg1, arg2) {
  return window['go']['api']['App']['UpdateAPIKey'](arg1, arg2);
}

export function UpdateModelName(arg1, arg2, arg3) {
  return window['go']['api']['App']['UpdateModelName'](arg1, arg2, arg3);
}

export function UpdateModelRule(arg1, arg2) {
  return window['go']['api']['App']['UpdateModelRule'](arg1, arg2);
}

export function UpdateProvider(arg1, arg2) {
  return window['go']['api']['App']['UpdateProvider'](arg1, arg2);
}
